---

  - name: Installing SQL Database for ubuntu
    apt:
      name:
        - mariadb-server
        - python3-pymysql
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: Editing the MariaDB file for ubuntu
    copy:
      dest: /etc/mysql/mariadb.conf.d/99-openstack.cnf
      content: |
        [mysqld]
        bind-address = 127.0.0.1

        default-storage-engine = innodb
        innodb_file_per_table = on
        max_connections = 4096
        collation-server = utf8_general_ci
        character-set-server = utf8
      mode: 0755
    when: ansible_distribution == "Ubuntu"

  - name: Stopping the database for ubuntu
    service:
      name: mysql
      state: stopped
    when: ansible_distribution == "Ubuntu"

  - name: Starting the database for ubuntu
    service:
      name: mysql
      state: started
    when: ansible_distribution == "Ubuntu"

  - name: Enabling the database for ubuntu
    service:
      name: mysql
      enabled: yes
    when: ansible_distribution == "Ubuntu"
